name: boring_app
description: App to help users find activities they can do when they are bored
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  bloc_test: ^9.1.4
  http: ^1.1.0
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  card_loading: ^0.3.0
  modal_bottom_sheet: ^2.1.2
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.4.5
  build_runner: ^2.4.6
  json_serializable: any
flutter:
  uses-material-design: true
  assets:
    - assets/images/